apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: kube-benco-io-cert
  namespace: dapr-store
spec:
  secretName: kube-benco-io-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.kube.benco.io"
  dnsNames:
    - "*.kube.benco.io"
