controller:
  service:
    labels:
      purpose: "daprstore-api-gateway"
  ingressClass: "dapr"
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/id: "api-gateway"
    dapr.io/port: "80"
  scope:
    enabled: true
