# helm install api-gateway stable/nginx-ingress -f ./deploy/ingress/chart-values.yaml
controller:
  ingressClass: "dapr"
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/id: "api-gateway"
    dapr.io/port: "80"
