#
# This file might sound important but...
# It is only used by the hosting on GitHub Pages, it has no other importance to the project!
#

title: "Dapr Store: A Dapr Reference App"
remote_theme: benc-uk/theme-msdark
favicon: https://azure-samples.github.io/dapr-store/web/frontend/public/logo.png
plugins:
  - jemoji
buttons:
  - b0:
    text: Main Guide
    href: https://azure-samples.github.io/dapr-store/
