apiVersion: v2
name: daprstore
description: A reference application showcasing the use of Dapr

type: application

# This is the chart version.
version: 0.6.0

# This is the version number of the application being deployed.
appVersion: 0.6.0
