emit:
  - "@typespec/openapi3"
  - "@typespec/json-schema"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/out"
    openapi-versions:
      - 3.1.0
  "@typespec/json-schema":
    emitter-output-dir: "{output-dir}/out/json-schema"
