apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: default
spec:
  httpPipeline:
    handlers:
    - name: uppercase 
      type: middleware.http.uppercase
  mtls:
    enabled: true
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"