settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: orders
  path: .
  commands: 
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - .
    - ../common
    ignored_paths:
    - .git
    - .realize
    - vendor
