apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "products"
        dapr.io/port: "9002"
    spec:
      containers:
      - name: service
        image: daprstore/products:dev
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 200M
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9002
            httpHeaders:
              - name: "No-Log"
                value: "true"            
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9002
            httpHeaders:
              - name: "No-Log"
                value: "true"            