apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100M
        ports:
        - containerPort: 6379

---

kind: Service
apiVersion: v1
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
