apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "cart"
        dapr.io/port: "9001"
    spec:
      containers:
      - name: service
        image: bcdemo.azurecr.io/dapr-store/cart
        imagePullPolicy: Always
        env:
          - name: DAPR_HTTP_PORT
            value: "3500"
        resources:
          limits:
            cpu: 200m
            memory: 200M