apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "cart"
        dapr.io/port: "9001"
        #dapr.io/config: "ratelimiting" # Uncomment to enable rate limiting
    spec:
      containers:
      - name: service
        image: daprstore/cart:latest
        imagePullPolicy: Always
        # env:
        #   - name: AUTH_CLIENT_ID
        #     value: "69972365-c1b6-494d-9579-5b9de2790fc3"            
        resources:
          limits:
            cpu: 100m
            memory: 200M
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9001
            httpHeaders:
              - name: "No-Log"
                value: "true"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9001
            httpHeaders:
              - name: "No-Log"
                value: "true"            