apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-host
  labels:
    app: frontend-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-host
  template:
    metadata:
      labels:
        app: frontend-host
    spec:
      containers:
      - name: service
        image: bcdemo.azurecr.io/dapr-store/frontend-host
        imagePullPolicy: Always
        ports:
        - containerPort: 8000        
        resources:
          limits:
            cpu: 100m
            memory: 50M

---

kind: Service
apiVersion: v1
metadata:
  name: frontend-host
  labels:
    app: frontend-host
spec:
  selector:
    app: frontend-host
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
