apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "orders"
        dapr.io/port: "9004"
    spec:
      containers:
      - name: service
        image: daprstore/orders
        imagePullPolicy: Always
        env:
          - name: DAPR_HTTP_PORT
            value: "3500"
          - name: AUTH_CLIENT_ID
            value: "69972365-c1b6-494d-9579-5b9de2790fc3"                  
        resources:
          limits:
            cpu: 100m
            memory: 200M