apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "users"
        dapr.io/port: "9003"
    spec:
      containers:
      - name: service
        image: bcdemo.azurecr.io/dapr-store/users
        imagePullPolicy: Always
        env:
          - name: DAPR_HTTP_PORT
            value: "3500"
        resources:
          limits:
            cpu: 200m
            memory: 200M