# ===================================================================
# File for the VS Code REST Client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Provides a quick way to test & call the API wihout needing Postman
# ===================================================================

@host = localhost:9000
@user = 00000000-1111-2222-3333-abcdef123456

# ===================================================================
# Products API
# ===================================================================

GET http://{{host}}/v1.0/invoke/products/method/catalog

###

GET http://{{host}}/v1.0/invoke/products/method/offers

###

GET http://{{host}}/v1.0/invoke/products/method/get/prd003

###

GET http://{{host}}/v1.0/invoke/products/method/search/Paisley



# ===================================================================
# Cart API
# ===================================================================

### Add products to cart
PUT http://{{host}}/v1.0/invoke/cart/method/setProduct/{{user}}/prd001/6

### Get cart
GET http://{{host}}/v1.0/invoke/cart/method/get/{{user}}

### Clear cart
PUT http://{{host}}/v1.0/invoke/cart/method/clear/{{user}}

### Submit cart
POST http://{{host}}/v1.0/invoke/cart/method/submit
content-type: application/json

"{{user}}"



# ===================================================================
# Orders API
# ===================================================================

### Get existing order
GET http://{{host}}/v1.0/invoke/orders/method/get/qf2ah 

### Get orders for user
GET http://{{host}}/v1.0/invoke/orders/method/getForUser/{{user}}



# ===================================================================
# Users API
# ===================================================================

### Check a user
GET http://{{host}}/v1.0/invoke/users/method/isregistered/{{user}}

### Get a user
GET http://{{host}}/v1.0/invoke/users/method/get/{{user}}

### Get a user from private endpoint
GET http://{{host}}/v1.0/invoke/users/method/private/get/{{user}}

### Register new user
POST http://{{host}}/v1.0/invoke/users/method/register
content-type: application/json

{
  "userId": "{{user}}",
  "email": "demo@example.net",
  "displayName": "API TEST"
}
