#
# Requires a ClusterIssuer to be setup
#

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: production-daprstore-cert
spec:
  secretName: production-daprstore-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 'production.daprstore.benco.io'
  dnsNames:
  - 'production.daprstore.benco.io'      
