name: CI Build Images

on: 
  push: 
    branches: [master]
    paths-ignore:
    - 'docs/**'
    - '.github/**'
    - 'etc/**'
    - 'scripts/**'
    - 'recycle-bin/**'
    - '.vscode/**'
  pull_request:
    branches: [master]
    
env:
  #DOCKER_TAG: ${{ github.run_id }}
  VERSION: 0.4.1
  DOCKER_REPO: daprstore  
  DOCKER_USER: bcdemo
  DOCKER_REG: bcdemo.azurecr.io

jobs:
  buildImages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Set Go version and paths
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'

    - name: Install any extra tools
      run: go get -u golang.org/x/lint/golint

    - name: Check code with gofmt, golint and ESLint
      run: make lint gofmt

    - name: Run unit tests
      run: make test

    - name: Run all builds
      run: |
        make docker DOCKER_TAG=${{ github.run_id }} VERSION=$VERSION
        make docker DOCKER_TAG=latest VERSION=$VERSION

    # =====================================================================
    # Steps after this are only run when merging or pushing into master
    # =====================================================================
    
    - name: Login to registry 
      if: github.event_name == 'push'
      run:  docker login $DOCKER_REG -u $DOCKER_USER -p ${{ secrets.ACR_PASSWORD }} 

    - name: Push to Dockerhub
      if: github.event_name == 'push'
      run: |
        make push DOCKER_TAG=${{ github.run_id }}
        make push DOCKER_TAG=latest

    # =====================================================================
    # Optional deployment trigger
    # =====================================================================

    - name: Trigger deployment
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DEPLOYMENT_PAT }}
        event-type: 'Continuous Deployment'
        client-payload: '{"imageTag": "${{ github.run_id }}"}'        