name: CI Build Images

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
env:
  DOCKER_TAG: latest
  DOCKER_REPO: daprstore  
  DOCKER_USER: bencuk
  DOCKER_REG: docker.io
  # DOCKER_USER: acr_name
  # DOCKER_REG: acr_name.azurecr.io

jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Set Go version and paths
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'

    - name: Install any extra tools
      run: go get -u golang.org/x/lint/golint

    - name: Check code with gofmt, golint and ESLint
      run: make lint gofmt

    - name: Run unit tests
      run: make test

    - name: Run all builds
      run: make docker DOCKER_TAG=latest VERSION=0.2.0

    # =====================================================================
    # Steps after this are only run when merging or pushing into master
    # =====================================================================

    - name: Run all builds with auth enabled
      run: make docker DOCKER_TAG=auth VERSION=0.2.0 CLIENT_ID="69972365-c1b6-494d-9579-5b9de2790fc3"
    
    - name: Login to registry 
      if: github.event_name == 'push'
      run:  docker login $DOCKER_REG -u $DOCKER_USER -p ${{ secrets.DOCKER_PASSWORD }} 

    - name: Push to Dockerhub
      if: github.event_name == 'push'
      run: make push DOCKER_TAG=latest
      run: make push DOCKER_TAG=auth
