name: CI Build Images

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
env:
  #DOCKER_TAG: dev
  VERSION: 0.4.0
  DOCKER_REPO: daprstore  
  DOCKER_USER: bcdemo
  DOCKER_REG: bcdemo.azurecr.io

jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Set Go version and paths
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'

    - name: Install any extra tools
      run: go get -u golang.org/x/lint/golint

    - name: Check code with gofmt, golint and ESLint
      run: make lint gofmt

    - name: Run unit tests
      run: make test

    - name: Run all builds
      run: make docker DOCKER_TAG=${{ github.run_id }} VERSION=$VERSION

    # =====================================================================
    # Steps after this are only run when merging or pushing into master
    # =====================================================================

    - name: Build frontend with auth enabled and clientId set
      run: make docker-frontend DOCKER_TAG=auth VERSION=$VERSION CLIENT_ID="69972365-c1b6-494d-9579-5b9de2790fc3"
    
    - name: Login to registry 
      if: github.event_name == 'push'
      run:  docker login $DOCKER_REG -u $DOCKER_USER -p ${{ secrets.ACR_PASSWORD }} 

    - name: Push to Dockerhub
      if: github.event_name == 'push'
      run: |
        make push DOCKER_TAG=$DOCKER_TAG
        docker push $DOCKER_REG/$DOCKER_REPO/frontend-host:auth

    # =====================================================================
    # Optional deployment trigger
    # =====================================================================

    - name: Trigger deployment
      uses: abendigo/create-deployment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        payload: '"imageTag": "${{ env.DOCKER_TAG }}"'
        description: "Deploy to Kubernetes demo environment"
        environment: "Kubernetes"