name: Deploy To Kubernetes

on:
 deployment:

jobs:
  deployStaging:
    if: github.event.deployment.environment == 'Kubernetes'
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.deployment.payload.imageTag }}

      - uses: benc-uk/deployment-status@v1
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}
          environment_url: "http://example.com/env"