name: Deploy To Kubernetes

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: "Image tag to deploy"
        required: true
        default: "latest"

env:
  IMAGE_REG: ghcr.io
  NAMESPACE: dapr-store

jobs:
  deploy-aks:
    name: "Deploy to AKS Cluster"
    runs-on: ubuntu-latest
    environment:
      name: "AKS Cluster"
      url: https://daprstore.kube.benco.io/

    env:
      NAMESPACE: "dapr-store"

    steps:
      - name: "Checkout source"
        uses: actions/checkout@v2

      - name: "Helm deploy Dapr Store app"
        uses: deliverybot/helm@master
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        with:
          helm: helm3
          release: store
          namespace: ${{ env.NAMESPACE }}
          chart: ./deploy/helm/daprstore
          value-files: ./deploy/live/app-values.yaml
          values: |
            image:
              tag: "${{ github.event.client_payload.IMAGE_TAG }}${{ github.event.inputs.IMAGE_TAG }}"

      - name: "Validate site is running"
        run: .github/scripts/url-check.sh -u https://daprstore.kube.benco.io/ -s "Dapr" -t 200 -c 5

      - name: "Run API tests"
        uses: matt-ball/newman-action@master
        with:
          collection: ./testing/postman_collection.json
          # Can't set this without a file, kinda lame
          environment: ./testing/postman_env_staging.json
          folder: "Smoke Tests"
