name: Deploy To Kubernetes

on:
 deployment:

jobs:
  deployStaging:
    if: startsWith(github.event.deployment.environment, 'Kubernetes')
    runs-on: ubuntu-latest

    env:
      STATIC_IP: '40.127.220.129'
      STATIC_IP_RG: 'MC_Demo.AKS_bcdemo_northeurope'

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Helm dependency update
        run: |
          helm dep update ./deploy/helm/daprstore

      - name: Helm deploy to staging
        uses: deliverybot/helm@v1
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        with:
          helm: helm3
          release: staging
          namespace: daprstore-stg
          chart: ./deploy/helm/daprstore
          values: |
            image:
              registry: bcdemo.azurecr.io
              repo: daprstore
              tag: "${{ github.event.deployment.payload.imageTag }}"
            apiGateway:
              staticIP:
                address: "${{ env.STATIC_IP }}"
                resourceGroup: "${{ env.STATIC_IP_RG }}"

      - name: Set deployment status - success
        if: ${{ success() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: success
          deployment_id: ${{ github.event.deployment.id }}
          environment_url: http://${{ env.STATIC_IP }}/

      - name: Set deployment status - failure
        if: ${{ failure() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: failure
          deployment_id: ${{ github.event.deployment.id }}       