name: Deploy To Kubernetes

#on:
# deployment:
on:
  repository_dispatch:
    types: [deploy]

env:
  STATIC_IP_RG: 'MC_Demo.AKS_bcdemo_northeurope'
  IMAGE_REG: bcdemo.azurecr.io
  IMAGE_REPO: daprstore

jobs:
  deployStaging:
    runs-on: ubuntu-latest

    env:
      STATIC_IP: '20.191.56.121'
      ENV_NAME: "Kubernetes: Staging"
      NAMESPACE: 'daprstore-stg'

    steps:
      - run: echo ${{ toJSON(github.event) }}

      - name: Start deployment
        id: deploy
        uses: abendigo/create-deployment@v1
        with:
          token: ${{ github.token }}
          environment: ${{ env.ENV_NAME }}

      - name: Checkout source
        uses: actions/checkout@v1

      - name: Helm dependency update
        run: |
          helm dep update ./deploy/helm/daprstore

      - name: Helm deploy to staging
        uses: deliverybot/helm@v1
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        with:
          helm: helm3
          release: daprstore
          namespace: ${{ env.NAMESPACE }}
          chart: ./deploy/helm/daprstore
          values: |
            image:
              registry: ${{ env.IMAGE_REG }}
              repo: ${{ env.IMAGE_REPO }}
              tag: "${{ github.event.repository_dispatch.client_payload.imageTag }}"
            apiGateway:
              staticIP:
                address: "${{ env.STATIC_IP }}"
                resourceGroup: "${{ env.STATIC_IP_RG }}"

      - name: Set deployment status - success
        if: ${{ success() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: success
          deployment_id: ${{ steps.deploy.outputs.id }}
          environment_url: http://${{ env.STATIC_IP }}/

      - name: Set deployment status - failure
        if: ${{ failure() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: failure
          deployment_id: ${{ steps.deploy.outputs.id }}       

# ==============================================================================================

  deployProduction:
    runs-on: ubuntu-latest
    needs: deployStaging

    env:
      STATIC_IP: '20.191.56.9'
      ENV_NAME: 'Kubernetes: Staging'
      NAMESPACE: 'daprstore'

    steps:
      - name: Start deployment
        id: deploy
        uses: abendigo/create-deployment@v1
        with:
          token: ${{ github.token }}
          environment: ${{ env.ENV_NAME }}

      - name: Checkout source
        uses: actions/checkout@v1

      - name: Helm dependency update
        run: |
          helm dep update ./deploy/helm/daprstore

      - name: Helm deploy to production
        uses: deliverybot/helm@v1
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBE_CONFIG }}
        with:
          helm: helm3
          release: daprstore
          namespace: ${{ env.NAMESPACE }}
          chart: ./deploy/helm/daprstore
          values: |
            image:
              registry: ${{ env.IMAGE_REG }}
              repo: ${{ env.IMAGE_REPO }}
              tag: "${{ github.event.repository_dispatch.client_payload.imageTag }}"
            apiGateway:
              staticIP:
                address: "${{ env.STATIC_IP }}"
                resourceGroup: "${{ env.STATIC_IP_RG }}"

      - name: Set deployment status - success
        if: ${{ success() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: success
          deployment_id: ${{ steps.deploy.outputs.id }}  
          environment_url: http://${{ env.STATIC_IP }}/

      - name: Set deployment status - failure
        if: ${{ failure() }}
        uses: benc-uk/deployment-status@v1
        with:
          token: ${{ github.token }}
          state: failure
          deployment_id: ${{ steps.deploy.outputs.id }}    