name: Release Versioned Images

on:
  release:
    types: [published]

env:
  IMAGE_REG: ghcr.io

jobs:
  release-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run all builds
        run: |
          make docker DOCKER_TAG=${{ github.event.release.tag_name }} VERSION=${{ github.event.release.tag_name }}
          make docker DOCKER_TAG=latest VERSION=${{ github.event.release.tag_name }}

      - name: Login to registry
        run: docker login $DOCKER_REG -u $DOCKER_USER -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Dockerhub
        run: |
          make push DOCKER_TAG=${{ github.event.release.tag_name }}
          make push DOCKER_TAG=latest
