name: Deploy 

on:
 deployment:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: http://example.com
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}
