name: Deploy 

on:
 deployment:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ toJson(github.event) }}

      - uses: benc-uk/deployment-status@v1
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}
          environment_url: "http://example.com/env"